// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import type { CustomDatabaseFunctions } from '../../types/supabase-extensions';

const SUPABASE_URL = "https://ieotixprkfglummoobkb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_hKQ8TsJxHlRcpowuOpIYzQ_vNuW9jXG";

// Merge custom functions with the auto-generated database type
type ExtendedDatabase = Database & {
  public: Database['public'] & {
    Functions: Database['public']['Functions'] & CustomDatabaseFunctions;
  };
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<ExtendedDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
  },
});